export const typography = {
  fonts: {
    primary: 'var(--font-mont)',
    secondary: 'var(--font-body)',
    tertiary: 'var(--font-secondary)',
  },
  sizes: {
    'display-xl': '72px',
    'display-lg': '64px',
    'heading-xl': '48px',
    'heading-lg': '36px',
    'heading-md': '24px',
    'heading-sm': '20px',
    'body-xl': '20px',
    'body-lg': '18px',
    'body': '16px',
    'body-sm': '14px',
    'caption': '12px',
    'overline': '12px',
  },
  lineHeights: {
    'display-xl': '1.05',
    'display-lg': '1.1',
    'heading-xl': '1.1',
    'heading-lg': '1.15',
    'heading-md': '1.2',
    'heading-sm': '1.3',
    'body-xl': '1.6',
    'body-lg': '1.65',
    'body': '1.65',
    'body-sm': '1.6',
    'caption': '1.5',
    'overline': '1.5',
  },
  tracking: {
    'display-xl': '-0.02em',
    'display-lg': '-0.01em',
    'heading-xl': '-0.01em',
    'heading-lg': '0',
    'heading-md': '0',
    'heading-sm': '0',
    'body-xl': '0',
    'body-lg': '0',
    'body': '0',
    'body-sm': '0',
    'caption': '0',
    'overline': '0.05em',
  },
  hero: {
    primary: {
      fontSize: "clamp(3.8rem, 5.5vw, 5.5rem)",
      fontWeight: "700",
      lineHeight: "0.9",
      letterSpacing: "-0.03em",
    },
    secondary: {
      fontSize: "clamp(3.0rem, 4.5vw, 4.4rem)",
      fontWeight: "500",
      fontStyle: "italic",
      lineHeight: "0.9",
      letterSpacing: "-0.03em",
    },
    accent: {
      fontSize: "clamp(4.0rem, 5.8vw, 5.8rem)",
      fontWeight: "800",
      lineHeight: "0.9",
      letterSpacing: "-0.03em",
    }
  }
} as const;
