import type { Client } from "@/types";

export const CLIENTS: Client[] = [
  { name: "Ivy Tree", logo: "ivytreeessex.co.uk.png", url: "https://www.ivytreeessex.co.uk/" },
  { name: "GBD", logo: "gbddoner.com.png", url: "https://www.greatbritishdoner.com/" },
  { name: "Biitest", logo: "easyfishoil-BcWQELwb.png", url: "https://biitest.com/" },
  { name: "Leila", logo: "leilabrasserie.co.uk.png", url: "https://leilabrasserie.co.uk/" },
  { name: "Carnivoor", logo: "carnivoorkitchen.com.png", url: "https://www.carnivoorkitchen.com/" },
  { name: "Direct Pizza", logo: "thedirectpizzaco.co.uk.jpg", url: "https://thedirectpizzaco.co.uk/index.php?page=home" },
  { name: "Sofra", logo: "sofra.co.uk.jpg", url: "https://www.sofra.co.uk/" },
  { name: "Jennys Café", logo: "jennys-brackleyonline.co.uk.png", url: "https://jennys-brackleyonline.co.uk/" },
  { name: "Antep Kitchen", logo: "antepkitchen.co.uk.jpg", url: "https://www.antepkitchen.co.uk/" },
  { name: "Gusto Ricco", logo: "gustoricco.com.png", url: "https://www.gustoricco.com/", keepOriginalColour: true },
  { name: "Masa", logo: "masarestaurant.com.tr-en.png", url: "https://www.masarestaurant.com.tr/en", keepOriginalColour: true },
  { name: "Pide Co", logo: "pide-co.com.png", url: "https://pide-co.com/", keepOriginalColour: true },
  { name: "Beboz", logo: "beboz-zebra-printer-logo.png", url: "https://www.beboz.com/" },
  { name: "Sensei 4", logo: "sensei4.png", url: "#" },
  { name: "Solo Kitchen", logo: "solokitchen.png", url: "https://www.thesolo.co.uk/" },
  { name: "The Shire grill", logo: "theshiregrill.co.uk.jpg", url: "https://theshiregrill.co.uk/" },
  { name: "Phoenix", logo: "phoenix-solutions-logo1.png", url: "#" },
  { name: "Mysa", logo: "mysarestaurant.co.uk.png", url: "http://mysarestaurant.co.uk/" },
  { name: "Zone", logo: "zone-essex.png", url: "#" },
  { name: "Anatolian Turkish Kitchen", logo: "anatolian--.png", url: "https://www.anatoliansouthampton.com/" },
  { name: "Turkuaz", logo: "turkuaz.png", url: "https://www.turkuaz-restaurant.co.uk/" },
  { name: "Lizz", logo: "lizz.png", url: "https://lizzrestaurant.co.uk/" },
  { name: "42 Holborn", logo: "42holborn.png", url: "https://42holborn.com/" },
  { name: "Alkis", logo: "alkisrestaurant-co-uk-bw.png", url: "https://www.alkisrestaurant.co.uk/", keepOriginalColour: true },
  { name: "Brudis", logo: "brudis.png", url: "#" },
  { name: "Brekky & Brunch", logo: "brekky.png", url: "#" },
  { name: "Liman", logo: "liman.png", url: "https://www.liman.co.uk/" },
  { name: "Swiss Sent", logo: "swiss sent.png", url: "#", keepOriginalColour: true },
  { name: "Rustiq", logo: "rustiq.png", url: "https://rustiqrestaurant.co.uk/" },
  { name: "Petrol Ofisi", logo: "petrol-ofisi.png", url: "https://www.petrolofisi.com.tr/" },
  { name: "Payiz", logo: "payiz.png", url: "https://payizrestaurant.co.uk/", keepOriginalColour: true },
  { name: "Otto Kitchen", logo: "otto.png", url: "https://otto-kitchen.co.uk/" },
  { name: "Leonidas", logo: "leonidas.png", url: "https://leonidas-lezzetleri.com.tr/" },
  { name: "Cutty Sark", logo: "cutty shark.png", url: "#" },
  { name: "Iznik", logo: "iznik.png", url: "https://iznik.co.uk/" },
  { name: "No5 Dining & Lounge", logo: "no5.png", url: "https://no5dining.co.uk/" },
  { name: "Mangal Meze", logo: "mangal.png", url: "https://www.mangalmeze.com/" }
];
